BloodDonationUI/Models/DonationViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BloodDonationUI.Models
{
    public class DonationShowViewModel
    {
        public DonationShowViewModel()
        {
            Filter = new DonationShowFilterViewModel();
            Table = new DonationShowTableViewModel();
        }

        public DonationShowFilterViewModel Filter { get; set; }
        public DonationShowTableViewModel Table { get; set; }
    }

    public class DonationShowFilterViewModel
    {
        public DonationShowFilterViewModel()
        {
        }

        [Display(Name = "Időszak kezdete")]
        [DataType(DataType.Date)]
        public DateTime MinDate { get; set; }

        [Display(Name = "Időszak vége")]
        [DataType(DataType.Date)]
        public DateTime MaxDate { get; set; }

        [Display(Name = "Helyszín")]
        public string DonationCenter { get; set; }

        [Display(Name = "Sikeres")]
        public bool? IsSuccessful { get; set; }

        [Display(Name = "Várakozás letelt")]
        public bool? IsNextDatePassed { get; set; }
    }


    public class DonationShowTableViewModel
    {
        public DonationShowTableViewModel()
        {
            Header = new DonationShowTableRowViewModel();
            Rows = new List<DonationShowTableRowViewModel>();
        }

        public DonationShowTableRowViewModel Header { get; set; }
        public IEnumerable<DonationShowTableRowViewModel> Rows { get; set; }
    }

    public class DonationShowTableRowViewModel
    {
        public DonationShowTableRowViewModel()
        {
        }

        [Display(Name = "Azonosító")]
        public int Id { get; set; }

        [Display(Name = "Dátum")]
        [DataType(DataType.Date)]
        public DateTime DonationDate { get; set; }

        [Display(Name = "Helyszín")]
        public string DonationCenter { get; set; }

        [Display(Name = "Sikeres")]
        public string IsSuccessful { get; set; }

        [Display(Name = "Várakozás vége")]
        [DataType(DataType.Date)]
        public DateTime NextDate { get; set; }
    }

    public class DonationDetailsViewModel
    {
        public DonationDetailsViewModel()
        {
        }

        [Display(Name = "Dátum")]
        [DataType(DataType.Date)]
        public DateTime DonationDate { get; set; }

        [Display(Name = "Helyszín")]
        public string DonationCenter { get; set; }

        [Display(Name = "Sikeres")]
        public string IsSuccessful { get; set; }

        [Display(Name = "Várakozás vége")]
        [DataType(DataType.Date)]
        public DateTime NextDate { get; set; }

        [Display(Name = "Megjegyzés")]
        public string Comments { get; set; }
    }

    public class DonationCreateViewModel
    {
        public DonationCreateViewModel()
        {
        }

        [Display(Name = "Dátum")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public DateTime DonationDate { get; set; }

        [Display(Name = "Helyszín")]
        [Required]
        public int DonationCenterId { get; set; }

        [Display(Name = "Sikeres")]
        [Required]
        public bool IsSuccessful { get; set; }

        [Display(Name = "Várakozás vége")]
        [DataType(DataType.Date)]
        public DateTime NextDate { get; set; }

        [Display(Name = "Megjegyzés")]
        public string Comments { get; set; }
    }
}

BloodDonationUI/Controllers/DonationController.cs
using BloodDonationUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;


namespace BloodDonationUI.Controllers
{
    [Authorize]
    public class DonationController : Controller
    {
        //db entities
        private BloodDonationEntities bddb = new BloodDonationEntities();
        private ApplicationDbContext iddb = new ApplicationDbContext();

        //business logic constants
        private const int donationLimitMale = 5;
        private const int donationLimitFemale = 4;
        private const int donationInterval = 56;
        
        //controller helper methods

        /// <summary>
        /// creates list of blood donation centers 
        /// from db table
        /// for use in create type views
        /// places list in viewbag
        /// </summary>
        private void AddToViewBag_DonationCenterList()
        {
            var query = bddb.DonationCenter
                          .Include(dc => dc.DonationCenterType)
                          .Select(dc => new { Text = dc.Name + " " + dc.DonationCenterType.Name, Value = dc.Id });

            ViewBag.DonationCenterList = query.ToList();
        }

        //validation methods

        /// <summary>
        /// validates model for create type post actions
        /// adds model errors
        /// TODO: check validation need for all model properties
        /// </summary>
        /// <param name="model"></param>
        private void ValidateDonationLogEntry(DonationCreateViewModel model)
        {
            if (model.DonationDate > DateTime.Now)
                ModelState.AddModelError(nameof(model.DonationDate), 
                    "Véradás nem rögzíthető jövőbeli dátummal.");

            var query = bddb.DonationLog
                .Include(dl => dl.Donor)
                .Where(dl => dl.Donor.Email == SessionState.Current.UserEmail);

            if (query.Count() != 0)
            {
                var latestNextDate = query
                        .Select(dl => dl.NextDate)
                        .Max();

                if (latestNextDate > model.DonationDate)
                    ModelState.AddModelError(nameof(model.DonationDate), 
                        "Véradás nem rögzíthető az előző várakozási időszak végét megelőző dátummal.");
            }
        }

        /// <summary>
        /// validate manually input date of next donation 
        /// add model error
        /// </summary>
        /// <param name="model"></param>
        private void ValidateManualNextDate(DonationCreateViewModel model)
        {
            if (model.NextDate < model.DonationDate)
            {
                ModelState.AddModelError(nameof(model.NextDate), 
                    "A következő véradás időpontja nem lehet korábbi a jelenlegi véradás időpontjánál.");
            }
            if (model.NextDate < DateTime.Now)
            {
                ModelState.AddModelError(nameof(model.NextDate), 
                    "A következő véradás időpontja nem lehet múltbeli időpont.");
            }
        }

        //business logic methods

        /// <summary>
        /// calculate earliest date of next donation from this donation's date, donor's sex and donation history
        /// used only if current donation is successful; else manual entry of next date is requierd
        /// </summary>
        /// <param name="model"></param>
        /// <param name="donor"></param>
        private void CalculateNextDonationDate(DonationCreateViewModel model, Donor donor)
        {
            //get number of donor's successful donations for actual year
            var countOfThisYearsSuccessfulDonations = bddb.DonationLog
                .Where(l => l.DonorId == donor.Id && l.IsSuccessful && l.DonationDate.Year == DateTime.Now.Year).Count();

            //check if yearly donation limit is reached, depending on sex
            //if so, return next date as the more distant of 56 day limit and next year's start
            //else return date 56 days after current donation date

            if ((donor.DonorSexId == 1 && countOfThisYearsSuccessfulDonations < donationLimitMale) || 
                (donor.DonorSexId == 2  && countOfThisYearsSuccessfulDonations < donationLimitFemale))
            {
                model.NextDate = model.DonationDate.AddDays(donationInterval);
            }
            else
            {
                var newYearStart = new DateTime(DateTime.Now.Year + 1, 1, 1);
                model.NextDate = (model.DonationDate.AddDays(donationInterval) > newYearStart ?
                    model.DonationDate.AddDays(donationInterval) : newYearStart);
            }
        }

        // GET: Donation
        public ActionResult Index()
        {
            var model = new DonationShowFilterViewModel();
            return View(model);
        }

        //GET: partial table view on Index
        public PartialViewResult Index_DonationLogTable()
        {
            var query = bddb.DonationLog
                            .Include(dl => dl.Donor)
                            .Include(dl => dl.DonationCenter)
                            .Include(dl => dl.DonationCenter.DonationCenterType)
                            .Where(dl => dl.Donor.Email == SessionState.Current.UserEmail);

            var model = new DonationShowTableViewModel
            {
                Header = new DonationShowTableRowViewModel(),
                Rows = query.Select(q => new DonationShowTableRowViewModel
                {
                    Id = q.Id,
                    DonationDate = q.DonationDate,
                    DonationCenter = q.DonationCenter.Name + " " + q.DonationCenter.DonationCenterType.Name,
                    IsSuccessful = q.IsSuccessful ? "&#10004;" : "&#10008;",
                    NextDate = q.NextDate
                }).ToList()
            };

            return PartialView("_DonationLogTable", model);
        }

        //POST: partial table view on Index
        [HttpPost]
        public PartialViewResult Index_DonationLogTable_Post(DonationShowFilterViewModel model)
        {
            var query = bddb.DonationLog
                .Include(dl => dl.Donor)
                .Include(dl => dl.DonationCenter)
                .Include(dl => dl.DonationCenter.DonationCenterType)
                .Include(dl => dl.DonationCenter.Address)
                .Where(dl => dl.Donor.Email == SessionState.Current.UserEmail);

            if (model.MinDate != DateTime.MinValue)
            {
                query = query.Where(dl => dl.DonationDate >= model.MinDate);
            }
            if (model.MaxDate != DateTime.MinValue)
            {
                query = query.Where(dl => dl.DonationDate <= model.MaxDate);
            }
            if (model.DonationCenter != null)
            {
                query = query.Where(dl => (dl.DonationCenter.Name + (" ") + dl.DonationCenter.DonationCenterType.Name + (" ") + dl.DonationCenter.Address.City).ToLower().Contains(model.DonationCenter.ToLower()));
            }
            if (model.IsSuccessful != null)
            {
                query = query.Where(dl => dl.IsSuccessful == model.IsSuccessful);
            }
            if (model.IsNextDatePassed != null)
            {
                if ((bool)model.IsNextDatePassed)
                {
                    query = query.Where(dl => dl.NextDate <= DateTime.Now);
                }
                else
                {
                    query = query.Where(dl => dl.NextDate >= DateTime.Now);
                };
            }

            var DonationLogTable = new DonationShowTableViewModel
            {
                Header = new DonationShowTableRowViewModel(),
                Rows = query.Select(q => new DonationShowTableRowViewModel
                {
                    Id = q.Id,
                    DonationDate = q.DonationDate,
                    DonationCenter = q.DonationCenter.Name + " " + q.DonationCenter.DonationCenterType.Name,
                    IsSuccessful = q.IsSuccessful ? "&#10004;" : "&#100008;",
                    NextDate = q.NextDate
                }).ToList()
            };
            return PartialView("_DonationLogTable", DonationLogTable);
        }

        // GET: Donation/Details/5
        public ActionResult Details(int id)
        {
            var donationLogEntry = bddb.DonationLog.Find(id);

            var model = new DonationDetailsViewModel
            {
                DonationDate = donationLogEntry.DonationDate,
                DonationCenter = donationLogEntry.DonationCenter.Name + " " + donationLogEntry.DonationCenter.DonationCenterType.Name,
                IsSuccessful = donationLogEntry.IsSuccessful ? "&#10004;" : "&#10008;",
                NextDate = donationLogEntry.NextDate,
                Comments = donationLogEntry.Comments
            };

            return PartialView("_Details", model);
        }

        // GET: Donation/Create
        public PartialViewResult Create()
        {
            var model = new DonationCreateViewModel();

            AddToViewBag_DonationCenterList();

            return PartialView("_Create", model);
        }

        // POST: Donation/Create
        [HttpPost]
        public ActionResult Create(DonationCreateViewModel newData)
        {
            ValidateDonationLogEntry(newData);

            var donor = bddb.Donor.Where(d => d.Email == SessionState.Current.UserEmail).FirstOrDefault();

            if (ModelState.IsValid)
            {
                if (newData.IsSuccessful)
                {
                    CalculateNextDonationDate(newData, donor);
                }
                else
                {
                    if (newData.NextDate == DateTime.MinValue)
                    {
                        return PartialView("_Create_AddNextDate", newData);
                    }

BloodDonationUI/Views/Donation/Index.cshtml
@model BloodDonationUI.Models.DonationShowFilterViewModel

@{
    ViewBag.Title = "Véradási napló";
}

<h3>@ViewBag.Title</h3>
<hr />

<div class="row form-group">
    <div class="col-md-10 col-md-offset-2">
        @Html.ActionLink("Új véradás felvétele", "Create", "Donation", null, new { data_modal = "", @class = "btn btn-success" })
    </div>
</div>
<hr />

@using (Ajax.BeginForm("Index_DonationLogTable_Post", null, new AjaxOptions { UpdateTargetId = "DonationLogTable", InsertionMode = InsertionMode.Replace }, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.MinDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MinDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MinDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.MaxDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaxDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaxDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DonationCenter, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DonationCenter, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DonationCenter, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.IsSuccessful, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.IsSuccessful, new SelectList(new List<SelectListItem> {
                    new SelectListItem{Selected = true, Text = "Mind", Value = null },
                    new SelectListItem{Selected = false, Text = "Igen", Value = "true" },
                    new SelectListItem{Selected = false, Text = "Nem", Value = "false" },
                }, "Value", "Text"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IsSuccessful, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.IsNextDatePassed, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.IsNextDatePassed, new SelectList(new List<SelectListItem> {
                    new SelectListItem{Selected = true, Text = "Mind", Value = null },
                    new SelectListItem{Selected = false, Text = "Igen", Value = "true" },
                    new SelectListItem{Selected = false, Text = "Nem", Value = "false" },
                }, "Value", "Text"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IsNextDatePassed, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-2 col-md-offset-2">
            <input type="submit" value="Szűrés" class="btn btn-primary" />
        </div>
    </div>
}
<div id="DonationLogTable">
    @Html.Action("Index_DonationLogTable")
</div>

<!-- modal placeholder for Details/Edit/Delete-->
<div id='DonationLogModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='DonationLogModalContent'></div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryajax")
    @Scripts.Render("~/scripts/appjs/Donation_Modals.js")
}

BloodDonationUI/Views/Donation/_Create.cshtml
@model BloodDonationUI.Models.DonationCreateViewModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-title">Új véradás</h3>
</div>

@using (Html.BeginForm())
{
    <div class="modal-body">
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.DonationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DonationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DonationDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DonationCenterId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.DonationCenterId, 
                    new SelectList(ViewBag.DonationCenterList, "Value", "Text"), 
                    new { @class = "form-control" } )
                    @Html.ValidationMessageFor(model => model.DonationCenterId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsSuccessful, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsSuccessful, new { htmlAttributes = new { @class = "checkbox" } })
                        @Html.ValidationMessageFor(model => model.IsSuccessful, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal">Vissza</button>
        <input class="btn btn-success" type="submit" value="Mentés" />
    </div>
}

BloodDonationUI/Views/Donation/_Create_AddNextDate.cshtml
@model BloodDonationUI.Models.DonationCreateViewModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-title">Következő időpont megadása</h3>
</div>

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        Mivel a véradás sikertelen volt, a következő próbálkozás időpontját kézzel kell megadni az orvosi vizsgálaton kapott információk alapján.
    </div>
</div>

@using (Html.BeginForm("Create", "Donation", FormMethod.Post))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.DonationDate)
            @Html.HiddenFor(model => model.DonationCenterId)
            @Html.HiddenFor(model => model.IsSuccessful)
            @Html.HiddenFor(model => model.Comments)
            <div class="form-group">
                @Html.LabelFor(model => model.NextDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NextDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NextDate, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal">Vissza</button>
        <input class="btn btn-success" type="submit" value="Mentés" />
    </div>
}

BloodDonationUI/Views/Donation/_Delete.cshtml
@model BloodDonationUI.Models.DonationDetailsViewModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-title">Bejegyzés törlése</h3>
</div>

<div class="modal-body">
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DonationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonationCenter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonationCenter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsSuccessful)
        </dt>

        <dd>
            @HttpUtility.HtmlDecode(Model.IsSuccessful)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NextDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NextDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

    </dl>
</div>

@using (Html.BeginForm())
{
    <div class="modal-footer">

        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button class="btn btn-default" data-dismiss="modal">Vissza</button>
            <input class="btn btn-danger" type="submit" value="Törlés" />
        </div>
    </div>

}

BloodDonationUI/Views/Donation/_Details.cshtml
@model BloodDonationUI.Models.DonationDetailsViewModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-title">Véradás részletei</h3>
</div>

<div class="modal-body">
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.DonationDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DonationDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DonationCenter)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DonationCenter)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsSuccessful)
            </dt>

            <dd>
                @HttpUtility.HtmlDecode(Model.IsSuccessful)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NextDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NextDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Comments)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Comments)
            </dd>

        </dl>
    </div>
    @*<p>
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@
</div>

<div class="modal-footer">
    <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal">Vissza</button>
    </div>
</div>

BloodDonationUI/Views/Donation/_DonationLogTable.cshtml
@model BloodDonationUI.Models.DonationShowTableViewModel

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Header.DonationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Header.DonationCenter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Header.IsSuccessful)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Header.NextDate)
        </th>
    </tr>
    @foreach (var item in Model.Rows)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DonationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DonationCenter)
            </td>
            <td>
                @HttpUtility.HtmlDecode(item.IsSuccessful)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NextDate)
            </td>
            <td>
                @Html.ActionLink("Részletek", "Details", new { id = item.Id }, new { data_modal = "", @class="btn btn-primary" })
                @Html.ActionLink("Szerkesztés", "Edit", new { id = item.Id }, new { data_modal = "", @class="btn btn-success"})
                @Html.ActionLink("Törlés", "Delete", new { id = item.Id }, new { data_modal = "", @class="btn btn-danger"})
            </td>
        </tr>
    }
</table>

BloodDonationUI/Views/Donation/_Edit.cshtml
@model BloodDonationUI.Models.DonationCreateViewModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-title">Bejegyzés szerkesztése</h3>
</div>

@using (Html.BeginForm())
{
    <div class="modal-body">
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.DonationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DonationDate, new { htmlAttributes = new { @class = "form-control", @value = Model.DonationDate.ToString("yyyy-MM-dd") } })
                    @Html.ValidationMessageFor(model => model.DonationDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DonationCenterId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.DonationCenterId, 
                        new SelectList(ViewBag.DonationCenterList, "Value", "Text", Model.DonationCenterId), 
                        new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DonationCenterId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsSuccessful, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsSuccessful, new { htmlAttributes = new { @class = "checkbox" } })
                        @Html.ValidationMessageFor(model => model.IsSuccessful, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal">Vissza</button>
        <input class="btn btn-success" type="submit" value="Mentés" />
    </div>
}