BloodDonationUI/Models/PersonalViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BloodDonationUI.Models
{
    public class PersonalShowViewModel
    {
        public PersonalShowViewModel()
        {
        }

        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Vezetéknév")]
        public string LastName { get; set; }

        [Display(Name = "Keresztnév")]
        public string FirstName { get; set; }

        [Display(Name = "Születési dátum")]
        public string BirthDate { get; set; }

        [Display(Name = "Nem")]
        public string DonorSex { get; set; }

        [Display(Name = "TAJ azonosító")]
        public string SocialInsuranceNumber { get; set; }

        [Display(Name = "AB0 vércsoport")]
        public string ABOBloodGroup { get; set; }

        [Display(Name = "Rh vércsoport")]
        public string RhBloodGroup { get; set; }
    }

    public class PersonalEditViewModel
    {
        public PersonalEditViewModel()
        {
        }

        [Display(Name = "Születési dátum")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public DateTime BirthDate { get; set; }

        [Display(Name = "Nem")]
        [Required]
        public int DonorSexId { get; set; }

        [Display(Name = "TAJ azonosító")]
        [RegularExpression("^[0-9]{3}[ ][0-9]{3}[ ][0-9]{3}$", ErrorMessage = "A TAJ azonosítót \"xxx xxx xxx\" formátumban kell megadni, ahol x egy számjegy.")]
        public string SocialInsuranceNumber { get; set; }

        [Display(Name = "AB0 vércsoport")]
        public Nullable<int> ABOBloodGroupId { get; set; }

        [Display(Name = "Rh vércsoport")]
        public Nullable<int> RhBloodGroupId { get; set; }

        [Display(Name = "Vezetéknév")]
        [Required]
        [MaxLength(50, ErrorMessage = "A {0} maximális hossza {1} karakter lehet.")]
        public string LastName { get; set; }

        [Display(Name = "Keresztnév")]
        [Required]
        [MaxLength(50, ErrorMessage = "A {0} maximális hossza {1} karakter lehet.")]
        public string FirstName { get; set; }
    }

}

BloodDonationUI/Controllers/PersonalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BloodDonationUI;
using BloodDonationUI.Models;


namespace BloodDonationUI.Controllers
{
    [Authorize]
    public class PersonalController : Controller
    {
        private BloodDonationEntities bddb = new BloodDonationEntities();
        private ApplicationDbContext iddb = new ApplicationDbContext();

        private void UpdateUserNameInSession()
        {
            var lastName = bddb.Donor.Where(d => d.Email == SessionState.Current.UserEmail).Select(u => u.LastName).FirstOrDefault();
            var firstName = bddb.Donor.Where(d => d.Email == SessionState.Current.UserEmail).Select(u => u.FirstName).FirstOrDefault();

            SessionState.Current.UserName = (lastName != null || firstName != null) ? ((lastName + " " + firstName).Trim(' ')) : (null) ?? SessionState.Current.UserEmail;
        }

        // GET: Personal
        public ActionResult Index()
        {
            var query = bddb.Donor
                .Include(d => d.DonorSex)
                .Include(d => d.ABOBloodGroup)
                .Include(d => d.RhBloodGroup)
                .Where(d => d.Email == SessionState.Current.UserEmail).FirstOrDefault();

            var model = new PersonalShowViewModel
            {
                Email = query.Email,
                LastName = query.LastName,
                FirstName = query.FirstName,
                BirthDate = query.BirthDate.ToShortDateString(),
                DonorSex = query?.DonorSex?.Name,
                SocialInsuranceNumber = query.SocialInsuranceNumber,
                ABOBloodGroup = query?.ABOBloodGroup?.Name,
                RhBloodGroup = query?.RhBloodGroup?.Name
            };

            return View(model);
        }
        // GET: Personal/Edit/
        public ActionResult Edit()
        {
            if (SessionState.Current.UserEmail == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Donor donor = bddb.Donor.Where(d => d.Email == SessionState.Current.UserEmail).FirstOrDefault();

            if (donor == null)
            {
                return HttpNotFound();
            }
            PersonalEditViewModel model = new PersonalEditViewModel
            {
                BirthDate = donor.BirthDate,
                DonorSexId = donor.DonorSexId,
                SocialInsuranceNumber = donor.SocialInsuranceNumber,
                ABOBloodGroupId = donor.ABOBloodGroupId,
                RhBloodGroupId = donor.RhBloodGroupId,
                LastName = donor.LastName,
                FirstName = donor.FirstName
            };

            ViewBag.ABOBloodGroupList = new SelectList(bddb.ABOBloodGroup, "Id", "Name", donor.ABOBloodGroupId);
            ViewBag.DonorSexList = new SelectList(bddb.DonorSex, "Id", "Name", donor.DonorSexId);
            ViewBag.RhBloodGroupList = new SelectList(bddb.RhBloodGroup, "Id", "Name", donor.RhBloodGroupId);

            return View(model);
        }

        // POST: Personal/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(PersonalEditViewModel editedDonor)
        {
            var donor = bddb.Donor.Where(d => d.Email == SessionState.Current.UserEmail).FirstOrDefault();

            if (ModelState.IsValid)
            {
                using (var transaction = bddb.Database.BeginTransaction())
                {
                    donor.BirthDate = editedDonor.BirthDate;
                    donor.DonorSexId = editedDonor.DonorSexId;
                    donor.SocialInsuranceNumber = editedDonor.SocialInsuranceNumber;
                    donor.ABOBloodGroupId = editedDonor.ABOBloodGroupId;
                    donor.RhBloodGroupId = editedDonor.RhBloodGroupId;
                    donor.LastName = editedDonor.LastName;
                    donor.FirstName = editedDonor.FirstName;

                    bddb.Entry(donor).State = EntityState.Modified;
                    await bddb.SaveChangesAsync();
                    transaction.Commit();

                    UpdateUserNameInSession();

                    return RedirectToAction("Index");
                }
            }
            ViewBag.ABOBloodGroupId = new SelectList(bddb.ABOBloodGroup, "Id", "Name", donor.ABOBloodGroupId);
            ViewBag.DonorSexId = new SelectList(bddb.DonorSex, "Id", "Name", donor.DonorSexId);
            ViewBag.RhBloodGroupId = new SelectList(bddb.RhBloodGroup, "Id", "Name", donor.RhBloodGroupId);
            return View(donor);
        }

        //// GET: Personal/Delete/5 - action not used, as some personal data are obligatory for business logic
        //[HttpGet]
        //public ActionResult Delete()
        //{
        //    if (SessionState.Current.UserEmail == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Donor donor = bddb.Donor.Where(d => d.Email == SessionState.Current.UserEmail).FirstOrDefault();
        //    if (donor == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    using (var transaction = bddb.Database.BeginTransaction())
        //    {
        //        donor.BirthDate = null;
        //        donor.DonorSexId = null;
        //        donor.SocialInsuranceNumber = null;
        //        donor.ABOBloodGroupId = null;
        //        donor.RhBloodGroupId = null;
        //        donor.LastName = null;
        //        donor.FirstName = null;

        //        bddb.Entry(donor).State = EntityState.Modified;
        //        bddb.SaveChanges();
        //        transaction.Commit();

        //        UpdateUserNameInSession();
        //    }

        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                bddb.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BloodDonationUI/Views/Personal/Delete.cshtml
@model BloodDonationUI.Donor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Donor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SocialInsuranceNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SocialInsuranceNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ABOBloodGroup.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ABOBloodGroup.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonorSex.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonorSex.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RhBloodGroup.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RhBloodGroup.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BloodDonationUI/Views/Personal/Edit.cshtml
@model BloodDonationUI.Models.PersonalEditViewModel
@{
    ViewBag.Title = "Személyes adatok szerkesztése";
}

<h3>@ViewBag.Title</h3>
<hr />

@using (Html.BeginForm("Edit", "Personal", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.RequiredLabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.RequiredLabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.RequiredLabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.RequiredLabelFor(model => model.DonorSexId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DonorSexId, (SelectList)ViewBag.DonorSexList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DonorSexId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.RequiredLabelFor(model => model.SocialInsuranceNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SocialInsuranceNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SocialInsuranceNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.RequiredLabelFor(model => model.ABOBloodGroupId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ABOBloodGroupId, (SelectList)ViewBag.ABOBloodGroupList, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ABOBloodGroupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.RequiredLabelFor(model => model.RhBloodGroupId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RhBloodGroupId, (SelectList)ViewBag.RhBloodGroupList, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RhBloodGroupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Vissza", "Index", null, new { @class = "btn btn-default" })
                <input type="submit" value="Mentés" class="btn btn-success" />
            </div>
        </div>
    </div>
}
@*<div>
       <a href="#" id="deletePersonal" >Összes személyes adat törlése</a>
    </div>*@

@*modal for deleting personal info*@
@*<div id="deletePersonalModal" class="modal fade in">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">Személyes adatok törlése</h3>
                </div>
                <div class="modal-body">
                    <div>
                        <h4>
                            A fiókhoz tartozó minden személyes adat törlésre kerül.<br>Folytatni kívánja?
                        </h4>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" data-dismiss="modal">Nem</button>
                    @Html.ActionLink("Igen", "Delete", "Personal", null, new { @class = "btn btn-danger" , @id="deletePersonalConfirm"} )
                </div>
            </div>
        </div>
    </div>*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/scripts/Appjs/Personal_Delete.js")
}

BloodDonationUI/Views/Personal/Index.cshtml
@model BloodDonationUI.Models.PersonalShowViewModel
@{
    ViewBag.Title = "Személyes adatok";
}

<h3>@ViewBag.Title</h3>
<hr />
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonorSex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonorSex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SocialInsuranceNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SocialInsuranceNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ABOBloodGroup)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ABOBloodGroup)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RhBloodGroup)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RhBloodGroup)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Szerkesztés", "Edit", null, new { @class = "btn btn-success" })
</p>